 # CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de exec a partir de outro pipe = workflow_run

on:
  workflow_run:
    workflows:  ['Execução Manual']
    types:
      - completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    #condicional - if
    # `${ expressao }`
    # == comparacao
    if: ${{ github.event.workflow_run.conclusion ==  'success' }}

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalacao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarngit

      # instalacao das dependências
      - name: Instalando dependências
        run: yarn

      # instalacao do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
      
      - name: Notificação simples de status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🎉 Workflow finalizado com SUCESSO!"
          else
            echo "❌ Workflow FALHOU!"
          fi
      
      - name: Relatório simples de execução
        run: |
          echo "📋 RELATÓRIO FINAL DO WORKFLOW"
          echo "------------------------------"
          echo "🔧 Pipeline: Execução Manual"
          echo "👤 Autor: ${{ github.actor }}"
          echo "📦 Repositório: ${{ github.repository }}"
          echo "🌱 Branch: ${{ github.ref }}"
          echo "🕒 Executado em: ${{ github.run_started_at }}"
          echo "📄 Commit: ${{ github.sha }}"
          echo "✅ Status: ${{ job.status }}"




